---
displayMode: compact
---
gantt
  title GANTT compact
  dateFormat  HH:mm:ss
  axisFormat  %Hh%M

  section DB Clean
  Clean: 12:00:00, 10m
  Clean: 12:30:00, 12m
  Clean: 13:00:00, 8m

  section Sessions
  A: 12:00:00, 63m
  B: 12:30:00, 12m
  C: 13:05:00, 12m
